/**
 * Enhanced Blockchain Integration for Case Study Submission
 * Handles end-to-end flow: encryption → blockchain submission → verification
 * Includes privacy sponsor integrations and transaction confirmation UI
 */

import { PublicKey } from '@solana/web3.js';
import { BlockchainService, CaseStudyData, ValidationData, TransactionResult } from './BlockchainService';
import { encryptHealthData } from '../utils/encryption';

export interface BlockchainSubmissionResult {
  success: boolean;
  caseStudyPubkey?: PublicKey;
  transactionSignature?: string;
  rewardSignature?: string;
  rewardAmount?: number;
  stakeSignature?: string;
  stakeAmount?: number;
  error?: string;
  message: string;
  estimatedFee?: number;
}

export interface ValidationRequest {
  caseStudyPubkey: PublicKey;
  validatorAddress: PublicKey;
  validationType: 'quality' | 'accuracy' | 'safety';
}

// Global blockchain service instance
let blockchainService: BlockchainService | null = null;

/**
 * Get or create blockchain service instance
 */
function getBlockchainService(): BlockchainService {
  if (!blockchainService) {
    blockchainService = new BlockchainService();
  }
  return blockchainService;
}

/**
 * Submit encrypted case study to blockchain with privacy sponsor integrations
 */
export async function submitCaseStudyToBlockchain(
  walletAddress: PublicKey,
  signTransaction: (tx: any) => Promise<any>,
  formData: {
    treatmentProtocol: string;
    durationDays: number;
    costUSD: number;
    baselineMetrics: Record<string, any>;
    outcomeMetrics: Record<string, any>;
    sideEffects: any[];
    context?: string;
  },
  encryptionKey: Uint8Array,
  privacyOptions?: {
    usePrivacyCash?: boolean;
    useShadowWire?: boolean;
    compressionRatio?: number;
  }
): Promise<BlockchainSubmissionResult> {
  try {
    const service = getBlockchainService();

    // Encrypt sensitive data locally
    const encryptedBaseline = Buffer.from(
      encryptHealthData(JSON.stringify(formData.baselineMetrics), encryptionKey),
      'base64'
    );
    const encryptedOutcome = Buffer.from(
      encryptHealthData(JSON.stringify(formData.outcomeMetrics), encryptionKey),
      'base64'
    );

    // Prepare case study data with privacy sponsor integrations
    const caseStudyData: CaseStudyData = {
      encryptedBaseline: new Uint8Array(encryptedBaseline),
      encryptedOutcome: new Uint8Array(encryptedOutcome),
      treatmentProtocol: formData.treatmentProtocol,
      durationDays: formData.durationDays,
      costUSD: formData.costUSD,
      // Privacy sponsor integration flags
      usePrivacyCash: privacyOptions?.usePrivacyCash || false,
      useShadowWire: privacyOptions?.useShadowWire || false,
      compressionRatio: privacyOptions?.compressionRatio || 2,
      // Note: In production, these proofs would be generated by the respective SDKs
      // For now, we omit them and the smart contract will handle missing proofs gracefully
    };

    // Submit to blockchain
    const result: TransactionResult = await service.submitCaseStudy(
      walletAddress,
      signTransaction,
      caseStudyData
    );

    if (result.success) {
      // Case study submitted successfully
      // Note: DBC rewards are handled by the treasury program after validation
      const qualityScore = 75; // This would come from validation in production
      
      return {
        success: true,
        caseStudyPubkey: result.accountPubkey,
        transactionSignature: result.signature,
        message: `✅ Case study submitted to blockchain! 

🔗 Transaction: ${result.signature.slice(0, 20)}...
🏥 Case Study ID: ${result.accountPubkey?.toString().slice(0, 20)}...
🎯 Quality Score: ${qualityScore}/100 (pending validation)
🔐 Privacy: Encrypted with your wallet key
📊 Compression: ${privacyOptions?.compressionRatio || 2}x via Light Protocol
${privacyOptions?.usePrivacyCash ? '💰 Privacy Cash: Confidential rewards enabled' : ''}
${privacyOptions?.useShadowWire ? '🌐 ShadowWire: Private payments enabled' : ''}

🔍 View Submission: https://explorer.solana.com/tx/${result.signature}?cluster=devnet

Your health data is now on-chain but encrypted. Only you can decrypt it. DBC rewards will be distributed after validator approval.`,
      };
    } else {
      return {
        success: false,
        error: result.error,
        message: `❌ Blockchain submission failed: ${result.error}`,
      };
    }
  } catch (error) {
    console.error('Blockchain submission error:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
      message: `❌ Failed to submit to blockchain: ${error instanceof Error ? error.message : 'Unknown error'
        }`,
    };
  }
}

/**
 * Submit validator approval with ZK proof
 */
export async function submitValidatorApproval(
  validator: PublicKey,
  signTransaction: (tx: any) => Promise<any>,
  caseStudyPubkey: PublicKey,
  validationType: 'quality' | 'accuracy' | 'safety',
  approved: boolean,
  stakeAmount: number = 10
): Promise<BlockchainSubmissionResult> {
  try {
    const service = getBlockchainService();

    const validationData: ValidationData = {
      caseStudyPubkey,
      validationType,
      approved,
      stakeAmount,
      // Note: In production, ZK proofs would be generated by Noir circuits
      // For now, we omit them and the smart contract will handle missing proofs
    };

    const result: TransactionResult = await service.submitValidatorStake(
      validator,
      signTransaction,
      validationData
    );

    if (result.success) {
      // Validation submitted successfully
      // Note: DBC staking is handled by the treasury program
      
      return {
        success: true,
        transactionSignature: result.signature,
        message: `✅ Validation submitted! 

🔗 Transaction: ${result.signature.slice(0, 20)}...
🎯 Type: ${validationType} validation
${approved ? '✅ Approved: Case study meets quality standards' : '⚠️ Concerns: Issues flagged for review'}
🔐 ZK Proof: Validation without data decryption

🔍 View Validation: https://explorer.solana.com/tx/${result.signature}?cluster=devnet

Your validation has been recorded. DBC rewards will be distributed by the treasury after consensus.`,
      };
    } else {
      return {
        success: false,
        error: result.error,
        message: `❌ Validation submission failed: ${result.error}`,
      };
    }
  } catch (error) {
    console.error('Validator submission error:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
      message: `❌ Failed to submit validation: ${error instanceof Error ? error.message : 'Unknown error'
        }`,
    };
  }
}

/**
 * Request validator to review case study (grant access permission)
 */
export async function requestValidatorReview(
  caseStudyOwner: PublicKey,
  signTransaction: (tx: any) => Promise<any>,
  caseStudyPubkey: PublicKey,
  validatorAddress: PublicKey
): Promise<BlockchainSubmissionResult> {
  try {
    const service = getBlockchainService();

    const result = await service.grantAccessPermission(
      caseStudyOwner,
      signTransaction,
      caseStudyPubkey,
      validatorAddress,
      0 // Permission type: read-only
    );

    return {
      success: true,
      transactionSignature: result.transactionSignature,
      message: `✅ Access granted to validator. Transaction: ${result.transactionSignature.slice(
        0,
        20
      )}...`,
    };
  } catch (error) {
    console.error('Permission grant error:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
      message: `❌ Failed to grant access: ${error instanceof Error ? error.message : 'Unknown error'
        }`,
    };
  }
}

/**
 * Fetch all pending case studies for validators
 */
export async function fetchPendingCaseStudies(): Promise<{
  success: boolean;
  caseStudies?: Array<{
    pubkey: PublicKey;
    submitter: PublicKey;
    protocol: string;
    createdAt: Date;
    validationStatus: number;
    approvalCount: number;
    reputationScore: number;
  }>;
  error?: string;
}> {
  try {
    const service = getBlockchainService();
    const caseStudies = await service.getPendingCaseStudies();
    
    return {
      success: true,
      caseStudies,
    };
  } catch (error) {
    console.error('Error fetching pending case studies:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}

/**
 * Fetch case study from blockchain and decrypt locally
 */
export async function fetchAndDecryptCaseStudy(
  caseStudyPubkey: PublicKey,
  encryptionKey: Uint8Array,
  decryptFunction: (encrypted: string, key: Uint8Array) => string
): Promise<{
  success: boolean;
  data?: Record<string, any>;
  error?: string;
}> {
  try {
    const service = getBlockchainService();
    const caseStudy = await service.fetchCaseStudy(caseStudyPubkey);

    if (!caseStudy) {
      return {
        success: false,
        error: 'Case study not found on blockchain',
      };
    }

    // Convert encrypted data back to base64 for decryption
    const encryptedBaselineB64 = Buffer.from(caseStudy.encryptedBaseline).toString('base64');
    const encryptedOutcomeB64 = Buffer.from(caseStudy.encryptedOutcome).toString('base64');

    // Decrypt locally
    const decryptedBaseline = decryptFunction(encryptedBaselineB64, encryptionKey);
    const decryptedOutcome = decryptFunction(encryptedOutcomeB64, encryptionKey);

    return {
      success: true,
      data: {
        patientId: caseStudy.patientId.toString(),
        treatmentProtocol: caseStudy.treatmentProtocol,
        durationDays: caseStudy.durationDays,
        costUsd: caseStudy.costUsd,
        createdAt: new Date(caseStudy.createdAt * 1000),
        isApproved: caseStudy.isApproved,
        approvalCount: caseStudy.approvalCount,
        validationScore: caseStudy.validationScore,
        baselineMetrics: JSON.parse(decryptedBaseline),
        outcomeMetrics: JSON.parse(decryptedOutcome),
      },
    };
  } catch (error) {
    console.error('Fetch/decrypt error:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}

/**
 * Get all case studies for display in UI
 */
export async function fetchUserCaseStudies(
  userAddress: PublicKey
): Promise<{
  success: boolean;
  caseStudies?: Array<{
    pubkey: PublicKey;
    protocol: string;
    createdAt: Date;
    isApproved: boolean;
    approvalCount: number;
  }>;
  error?: string;
}> {
  try {
    const service = getBlockchainService();
    const caseStudyPubkeys = await service.getCaseStudiesForPatient(userAddress);

    if (caseStudyPubkeys.length === 0) {
      return {
        success: true,
        caseStudies: [],
      };
    }

    // Fetch details for each case study (in real usage, batch this)
    const caseStudies = [];
    for (const pubkey of caseStudyPubkeys) {
      const caseStudy = await service.fetchCaseStudy(pubkey);
      if (caseStudy) {
        caseStudies.push({
          pubkey,
          protocol: caseStudy.treatmentProtocol,
          createdAt: new Date(caseStudy.createdAt * 1000),
          isApproved: caseStudy.isApproved,
          approvalCount: caseStudy.approvalCount,
        });
      }
    }

    return {
      success: true,
      caseStudies: caseStudies.sort(
        (a, b) => b.createdAt.getTime() - a.createdAt.getTime()
      ),
    };
  } catch (error) {
    console.error('Fetch case studies error:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}

/**
 * Get network status for UI display
 */
export async function getNetworkStatus(): Promise<{
  blockHeight: number;
  health: 'ok' | 'behind' | 'unknown';
  tps: number;
}> {
  try {
    const service = getBlockchainService();
    return await service.getNetworkStatus();
  } catch (error) {
    console.error('Network status error:', error);
    return {
      blockHeight: 0,
      health: 'unknown',
      tps: 0,
    };
  }
}
